### ISSUE TITLE
Wrong machineID results

### ISSUE THREAD

**Issue by dvrkps** [tinrab/makaroni#1]
Hi @tinrab 

net.ParseIP always return ip []byte with length of 16.

https://github.com/tinrab/makaroni/blob/master/utilities/unique-id/main.go#L54-L58

**Comment by dvrkps** [comment]
@tinrab ping :)

**Comment by tinrab** [comment]
What exactly is the problem then?

**Comment by dvrkps** [comment]
hi @tinrab : len for valid net.IP is always 16.

https://play.golang.org/p/gI6Gf60xp3z

maybe wrong indexes in uint16(ip[2])<<8 + uint16(ip[3]) 
first 8 bytes for ipv4 is zero.

and check for invalid ip : 
```
if ip==nil {
        ...
}
```

**Comment by tinrab** [comment]
I've fixed it now.
